services:
#  lending-agent-no-wallet:
#    build:
#      context: ./
#      dockerfile: community/lending-agent-no-wallet/Dockerfile
#    container_name: vibekit-lending-agent-no-wallet
#    env_file:
#      - path: .env
#        required: true
#      - path: community/lending-agent-no-wallet/.env
#        required: false
#    ports:
#      - 3001:3001
#    restart: unless-stopped
#
#  swapping-agent-no-wallet:
#    build:
#      context: ./
#      dockerfile: community/swapping-agent-no-wallet/Dockerfile
#    container_name: vibekit-swapping-agent-no-wallet
#    env_file:
#      - path: .env
#        required: true
#      - path: community/swapping-agent-no-wallet/.env
#        required: false
#    ports:
#      - 3005:3005
#    restart: unless-stopped
#
#  coingecko-mcp-server:
#    build:
#      context: ./
#      dockerfile: lib/community-mcp-tools/coingecko-mcp-server/Dockerfile
#    container_name: vibekit-coingecko-mcp-server
#    env_file:
#      - path: .env
#        required: true
#    ports:
#      - 3011:3011
#    restart: unless-stopped
#
#  defisafety-agent:
#    build:
#      context: ./
#      dockerfile: templates/defisafety-agent/Dockerfile
#    container_name: vibekit-defisafety-agent
#    env_file:
#      - path: .env
#        required: true
#      - path: templates/defisafety-agent/.env
#        required: false
#    environment:
#      - PORT=3010
#    ports:
#      - 3010:3010
#    restart: unless-stopped

  # langgraph-workflow-agent:
  #   build:
  #     context: ./
  #     dockerfile: templates/langgraph-workflow-agent/Dockerfile
  #   container_name: vibekit-langgraph-workflow-agent
  #   env_file:
  #     - path: .env
  #       required: true
  #     - path: templates/langgraph-workflow-agent/.env
  #       required: false
  #   ports:
  #     - 3009:3009
  #   restart: unless-stopped

  # quickstart-agent-template:
  #   build:
  #     context: ./
  #     dockerfile: templates/quickstart-agent/Dockerfile
  #   container_name: vibekit-quickstart-agent-template
  #   env_file:
  #     - path: .env
  #       required: true
  #     - path: templates/quickstart-agent/.env
  #       required: false
  #   ports:
  #     - 3007:3007
  #   restart: unless-stopped

  # allora-price-prediction-agent:
  #   build:
  #     context: ./
  #     dockerfile: templates/allora-price-prediction-agent/Dockerfile
  #   container_name: vibekit-allora-price-prediction-agent
  #   env_file:
  #     - path: .env
  #       required: true
  #     - path: templates/allora-price-prediction-agent/.env
  #       required: false
  #   ports:
  #     - 3008:3008
  #   restart: unless-stopped

  # liquidity-agent-no-wallet:
  #   build:
  #     context: ./
  #     dockerfile: community/liquidity-agent-no-wallet/Dockerfile
  #   container_name: vibekit-liquidity-agent-no-wallet
  #   env_file:
  #     - path: .env
  #       required: true
  #     - path: community/liquidity-agent-no-wallet/.env
  #       required: false
  #   ports:
  #     - 3002:3002
  #   restart: unless-stopped

  # pendle-agent:
  #   build:
  #     context: ./
  #     dockerfile: community/pendle-agent/Dockerfile
  #   container_name: vibekit-pendle-agent
  #   env_file:
  #     - path: .env
  #       required: true
  #     - path: community/pendle-agent/.env
  #       required: false
  #   ports:
  #     - 3003:3003
  #   restart: unless-stopped

  # swapping-agent:
  #   build:
  #     context: ./
  #     dockerfile: community/swapping-agent/Dockerfile
  #   container_name: vibekit-swapping-agent
  #   env_file:
  #     - path: .env
  #       required: true
  #     - path: community/swapping-agent/.env
  #       required: false
  #   ports:
  #     - 3004:3004
  #   restart: unless-stopped

  web:
    container_name: vibekit-web-app
    build:
      context: ./
      dockerfile: clients/web/Dockerfile.prod
    env_file:
      - .env
    environment:
      POSTGRES_URL: postgresql://chatbot:changeme@db:5432/chatbot
      AUTH_URL: http://localhost:3000/api/auth
      PORT: 3000
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: vibekit-db
    environment:
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: chatbot
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
