packages:
  - 'lib/**/*'
  - 'examples/*'
  - 'templates/*'
  - 'clients/*'
  - 'onchain-actions-plugins/**/*'

catalog:
  # Core dependencies
  zod: ^4.0.0
  '@modelcontextprotocol/sdk': ^1.18.2
  dotenv: ^17.2.3
  ai: ^5.0.59
  express: ^5.1.0
  '@openrouter/ai-sdk-provider': ^1.2.0
  '@emberai/arbitrum-vibekit-core': ^0.1.2

  # Dev dependencies
  '@types/node': ^22.0.0
  typescript: ^5.9.2
  tsx: ^4.20.6
  prettier: ^3.6.2

  # Testing
  '@types/chai': ^4.3.11
  '@types/mocha': ^10.0.6
  chai: ^6.2.0
  mocha: ^11.7.3
  mocha-suppress-logs: ^0.5.1
  vitest: ^3.2.4
  c8: ^10.1.3

  # Linting
  eslint: ^9.36.0
  '@eslint/js': ^9.36.0
  eslint-config-prettier: ^9.1.0

  # Build tools
  '@typescript-eslint/eslint-plugin': ^8.0.0
  '@typescript-eslint/parser': ^8.0.0
  typescript-eslint: ^8.0.0
